defaults:
  - mettagrid
  - game/map_builder: simple
  - _self_

game:
  num_agents: 24

  mab_builder:
    room:
      objects:
        mine: 10
        generator: 2
        altar: 1
        armory: 1
        lasery: 1
        block: 20
        wall: 20

        temple: 0
        lab: 0
        factory: 0

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    put_items:
      enabled: true
    get_items:
      enabled: true
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false
