defaults:
  - common
  - wandb: metta_research
  - sim: all
  - _self_

run: ???
policy_uri: ???

sim_job:
  policy_uris:
    - ${policy_uri}
  simulation_suite: ${sim}
  replay_dir: ${run_dir}/replays/evals
  stats_db_uri: ???

cmd: sim
