defaults:
  - common
  - wandb: metta_research
  - sim: all
  - _self_

run: ???

sim_job:
  use_llm_agent: true
  policy_uris: []  # Not used when use_llm_agent is true
  simulation_suite: ${sim}
  stats_dir: ${run_dir}/stats
  stats_db_uri: ${run_dir}/stats.db
  replay_dir: ${run_dir}/replays/evals

cmd: sim
